# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(db_index=True, max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('address', models.CharField(max_length=500)),
                ('contact_number', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'enrollment_registrant',
            },
        ),
    ]
