# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='contact_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
